name: Chromatic

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.chpt_d63530b3ef235e6 }}
        run: npx chromatic run --exit-zero-on-changes
